"""price and type_of

Revision ID: 1a70369eef6e
Revises: b727a02986d1
Create Date: 2022-12-14 09:20:09.856591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a70369eef6e'
down_revision = 'b727a02986d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('price')
        batch_op.drop_column('type_of')

    # ### end Alembic commands ###
