"""se establece relacion entre talas users y messages

Revision ID: 8406172a8e18
Revises: 205f03376c6d
Create Date: 2022-12-08 22:49:34.137524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8406172a8e18'
down_revision = '205f03376c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
