"""tabla sizelinks

Revision ID: 914e61f1d7a1
Revises: 1a70369eef6e
Create Date: 2022-12-14 10:01:54.941774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914e61f1d7a1'
down_revision = '1a70369eef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=False),
    sa.Column('size', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sizes')
    # ### end Alembic commands ###
