"""add price to sizes

Revision ID: bb6fb19e4dd8
Revises: 914e61f1d7a1
Create Date: 2022-12-14 10:13:14.491424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb6fb19e4dd8'
down_revision = '914e61f1d7a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.alter_column('size',
               existing_type=sa.TEXT(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sizes', schema=None) as batch_op:
        batch_op.alter_column('size',
               existing_type=sa.String(length=120),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('price')

    # ### end Alembic commands ###
