"""borra type_of y agrega price y link

Revision ID: cd8103975387
Revises: eca742e7e7e6
Create Date: 2022-12-14 22:50:16.607146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd8103975387'
down_revision = 'eca742e7e7e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=100), nullable=True))
        batch_op.drop_column('type_of')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_of', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('link')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
